/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public\\FilmCamera.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/FilmCamera.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="#CAM0001_Body" geometry={nodes['#CAM0001_Body'].geometry} material={materials['#CAM0001_Textures']} morphTargetDictionary={nodes['#CAM0001_Body'].morphTargetDictionary} morphTargetInfluences={nodes['#CAM0001_Body'].morphTargetInfluences}>
        <mesh geometry={nodes['#CAM0001_Battery_Check'].geometry} material={materials['#CAM0001_Textures']} position={[0.05, 0.07, 0]} />
        <mesh geometry={nodes['#CAM0001_Film_Advance'].geometry} material={materials['#CAM0001_Textures']} position={[-0.06, 0.08, 0]} />
        <mesh geometry={nodes['#CAM0001_Shutter'].geometry} material={materials['#CAM0001_Textures']} position={[-0.03, 0.08, 0.01]} />
        <mesh geometry={nodes['#CAM0001_Shutter_Speed'].geometry} material={materials['#CAM0001_Textures']} position={[-0.06, 0.07, 0]} />
        <mesh geometry={nodes['#CAM0001_Spool'].geometry} material={materials['#CAM0001_Textures']} position={[0.05, 0.08, 0]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/FilmCamera.glb')
