/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/guy.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/guy.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="MikeAlger" position={[-1.16, -0.4, -0.77]} rotation={[Math.PI / 2, 0, -1.78]} scale={0.01}>
          <group name="Subdivision_Surface" />
          <group name="Subdivision_Surface_2" />
          <group name="Subdivision_Surface_3" />
          <group name="Subdivision_Surface_4" />
          <group name="Subdivision_Surface_5" />
          <group name="Subdivision_Surface_6" />
          <primitive object={nodes.mixamorig_Hips} />
          <skinnedMesh name="Bracelet" geometry={nodes.Bracelet.geometry} material={materials['MikeAlger_Material.1']} skeleton={nodes.Bracelet.skeleton} />
          <skinnedMesh name="Hair" geometry={nodes.Hair.geometry} material={materials['MikeAlger_Material.4']} skeleton={nodes.Hair.skeleton} />
          <skinnedMesh name="Pants" geometry={nodes.Pants.geometry} material={materials['MikeAlger_Material.3']} skeleton={nodes.Pants.skeleton} />
          <skinnedMesh name="Shirt" geometry={nodes.Shirt.geometry} material={materials['MikeAlger_Material.5']} skeleton={nodes.Shirt.skeleton} />
          <skinnedMesh name="Shoes" geometry={nodes.Shoes.geometry} material={materials['MikeAlger_Material.6']} skeleton={nodes.Shoes.skeleton} />
          <skinnedMesh name="Sweatshirt" geometry={nodes.Sweatshirt.geometry} material={materials['MikeAlger_Material.2']} skeleton={nodes.Sweatshirt.skeleton} />
          <skinnedMesh name="Body" geometry={nodes.Body.geometry} material={materials.MikeAlger_Material} skeleton={nodes.Body.skeleton} morphTargetDictionary={nodes.Body.morphTargetDictionary} morphTargetInfluences={nodes.Body.morphTargetInfluences} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/guy.glb')
